<a href="https://colab.research.google.com/github/ayushmeharkure13/my_first_repos/blob/main/Copy_of_numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a.ndim)
print(a/2)
for i in a/2:
  print(i)

1
[0.5 1.  1.5 2.  2.5]
0.5
1.0
1.5
2.0
2.5


 Might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [ ]:
for i in a/2:
  print(i)

0.5
1.0
1.5
2.0
2.5


In [ ]:
 #If you expect your integer arrays to be a specific type, then
 #you need to specify the dtype while you create the array.
b=np.array([2,123,4,124] , dtype=np.int8)
print(b)
c=np.array([2,129,4,134] , dtype=np.int8)
print(c)
#it generates the wrong o/p because the size of signed integer of 8 bytes is from -128 to +127
#here we write 129 ,135 which is out of range

[  2 123   4 124]
[   2 -127    4 -122]


# **Functions for array creation in numpy**


###for 1-d array:-    np.array( [ #content# ] )
###for 2-d array:-    np.array([ [ #content# ] , [ #content# ] ]) or np.array(([content ] , [content]))




In [ ]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b=np.ones(4)
b

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.empty(4)       #it prints any random values

array([ 2.5,  5. ,  7.5, 10. ])

In [ ]:
c=np.arange(2,9,2)   #start=2,stop=9,end=9-1=8,step=2
c

array([2, 4, 6, 8])

In [ ]:
a=np.random.randint(5,50,40)         #40 random values will be printed in between 5 to 50
a

array([37, 25, 43, 23, 48, 24, 16,  5, 16, 32, 34,  6, 10, 29, 12, 47, 16,
       36, 18, 28,  5, 43, 23, 26, 36, 49, 17, 46, 48, 24, 39, 40, 41, 13,
       42, 44,  6, 46, 13, 43])

In [ ]:
iden=np.identity(5)     #it will generate 5 cross 5 wala identity matrx
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Specifying your data type

### While the default data type is floating point (np.float64),we can explicitly specify which data type we want using the dtype keyword.dtype is highly efficient for memory management.


In [ ]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a=np.arange(2,5,0.5)
print(a)

[2.  2.5 3.  3.5 4.  4.5]


In [ ]:
for i in a:
  print(i,end=" ")

2.0 2.5 3.0 3.5 4.0 4.5 


The linspace() function in NumPy creates an array of evenly spaced numbers over a specified range. The range is defined by the start and end points of the sequence, and the number of evenly spaced points to be generated between them.
###**numpy.linspace(start, stop, num, endpoint, retstep, ...)**

In [ ]:
print(np.linspace(0,10,6))

[ 0.  2.  4.  6.  8. 10.]


In [ ]:
np.linspace(1,7,5)      #1 is start , end is considered as 7 and 5 is number of spacing which we want

array([1. , 2.5, 4. , 5.5, 7. ])

In [ ]:
a=np.array([2,3,4,5,6])
a[3]=56
print(a)

[ 2  3  4 56  6]


In [ ]:
#manipulation in numpy array
x=np.array([[1,2,3,4,5,6],
          [7,8,9,10,11,12]])
x[1,3]=45
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 45 11 12]]


In [ ]:
#numpy.linspace will create arrays with a specified number of elements,
#and spaced equally between the specified beginning and end values. For example:
np.linspace(1., 4., 6)
#here start value is 1 end value is 4 and step value is 0.6

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

# 2-D array creation function and few basic opearations on it


In [ ]:
a=np.arange(1,5,1)
print(a)
print(a.ndim)
print(a[0])

[1 2 3 4]
1
1


In [ ]:
b=np.array(([1,2,3,4,5,6],
            [7,8,9,1,2,3]))
print(b.ndim)
print(f"element at 0,1 position of an array is {b[0,4]}")

2
element at 0,1 position of an array is 5


In [ ]:
a=np.array([23,454,54,34])
print(a[3])
b=np.array(([12,23,15,12],    #00 01 02 03
            [23,76,43,10]))   #10 11 12 13
print(b[0,2])

34
15


In [ ]:
import numpy as np
a=np.array([1,2,4,5,6])
b=np.array([[2,3,4],
            [2,3,4]])
c= np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]]
])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## Sorting and Concatenating an array

In [ ]:
a=np.array([2,1,4,56,3,90,21])
np.sort(a)

array([ 1,  2,  3,  4, 21, 56, 90])

In [ ]:
a=np.array([1,4,2,3,4,5,2,1,56,32])
np.sort(a)

array([ 1,  1,  2,  2,  3,  4,  4,  5, 32, 56])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,9,10])
print(np.concatenate((a,b)))

[ 1  2  3  4  5  6  7  9 10]


In [ ]:
c=np.array(([23,45,56,78],
            [12,13,14,15]))
d=np.array(([1,2,3,4],
            [5,6,7,8]))
print(np.concatenate((c,d),axis=0))
print(np.concatenate((c,d),axis=1 ))

[[23 45 56 78]
 [12 13 14 15]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[23 45 56 78  1  2  3  4]
 [12 13 14 15  5  6  7  8]]


In [ ]:
x = np.array([[1, 2], [3, 4]])     #00 01 10 11
print(x[0,0],x[0,1],x[1,0],x[1,1])
print(x.ndim)
y = np.array([[5, 6],[3,4]])
print(y.ndim)
np.concatenate((x,y),axis=1)

1 2 3 4
2
2


array([[1, 2, 5, 6],
       [3, 4, 3, 4]])

In [ ]:
a=np.array([[1,2,3,4],                          #b=np.array(([12,13,14,15],
            [5,6,7,8]])
print(a)                       #            [16,17,18,19]))
b=np.array(([12,13,14,15],
            [16,17,18,19]))
print(a.ndim,b.ndim)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))
print(np.sum((a,b) , axis=0))
print(np.sum((a,b), axis=1))

[[1 2 3 4]
 [5 6 7 8]]
2 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [12 13 14 15]
 [16 17 18 19]]
[[ 1  2  3  4 12 13 14 15]
 [ 5  6  7  8 16 17 18 19]]
[[13 15 17 19]
 [21 23 25 27]]
[[ 6  8 10 12]
 [28 30 32 34]]


In [ ]:
print(np.sum((a,b) , axis=0))

[[13 15 17 19]
 [21 23 25 27]]


In [ ]:
print(np.sum((a,b), axis=1))

[[ 6  8 10 12]
 [28 30 32 34]]


In [ ]:
a='73,456'
print(type(a))

<class 'str'>


In [ ]:
x=a.split()[0].replace(',','')

In [ ]:
int_value=np.array(x,dtype='int')                         #converted the string value'73,456' int integer
print(int_value)

73456


ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3)

In [ ]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print(np.size(a))
print(np.shape(a))

8
(2, 4)


In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x.ndim)
x[6]
np.size(x)
print(x)
x.reshape(3,3)           #here i reshaped the 1-d array to 2-d array as 3 rows and 3 columns

1
[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.arange(1,16,2)
print(a)
print(a.reshape(2,4))
print(a.reshape(4,2))

[ 1  3  5  7  9 11 13 15]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [ ]:
a=np.array([[[1,2,3] , [5,6,7] , [9,10,11]]])
a

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(1, 3, 3)

In [ ]:
a.size

9

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape

(1, 3, 3)

In [ ]:
my_array=np.arange(50)
print(my_array)
my_array.reshape(2,25)
my_array=my_array.reshape(25,2)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]


In [ ]:
print(my_array.shape)
print(my_array.size)

(25, 2)
50


In [ ]:
a=np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

###The ravel() function in numpy is used to flatten a multi-dimensional array into a contiguous 1-D array. The returned array has the same elements as the input array, but in a single dimension.
**The syntax for the ravel() function is:**
###**np.ravel(array, order='C')**

In [ ]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

#Array operations

In [ ]:
my_arr=[[1,6,3] , [4,2,8] , [7,9,1] ]
a=np.array(my_arr)
a

array([[1, 6, 3],
       [4, 2, 8],
       [7, 9, 1]])

In [ ]:
a.sum(axis=0)

array([12, 17, 12])

In [ ]:
ap-.sum(axis=1)

array([10, 14, 17])

In [ ]:
a.T   #transpose of array a

array([[1, 4, 7],
       [6, 2, 9],
       [3, 8, 1]])

In [ ]:
a.flat

In [ ]:
for i in a.flat:
  print(i)

1
6
3
4
2
8
7
9
1


In [ ]:
a.nbytes   #no of bytes consumed

72

In [ ]:
x=np.array([111,13,56,43,45])


In [ ]:
x.argmax()    #returns the index of greatest element is an array

2

In [ ]:
x.argmin()

1

In [ ]:
x.argsort()         #returns the index of elements to be sorted in ascending order

array([1, 3, 4, 2, 0])